exercicios da aula 8
yurearaujo/estudoads pull request #5
Opened 2023-01-24 22:48 UTC by Ceciliamelo97

exercicios da aula 8

2023-01-25 00:35 UTC, yurearaujo commented on Cecilia/ex018.py
> +a = s
Precisa finalizar, por gentileza

2023-01-25 00:36 UTC, yurearaujo requested changes

2023-01-25 00:36 UTC, yurearaujo commented on Cecilia/ex018.py
> +a = s
Precisa finalizar, por gentileza

2023-01-27 18:30 UTC, Ceciliamelo97 commented on Cecilia/ex018.py
> +a = s
finalizado!

2023-01-31 23:48 UTC, yurearaujo approved these changes
10/10!!!

2023-01-31 23:50 UTC, merged